// Generated by scripts/generate-filter-table.mjs from the x-profound-filter-grammar
// extension of the Profound OpenAPI spec. Do not edit by hand.

export const MAX_DEPTH = 3;

export const FIELD_TABLE = {
  analysis_type: {
    layer: 'entity',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
    ],
  },
  citation_category: {
    layer: 'entity',
    ops: [
      'is',
      'in',
    ],
  },
  citation_tag: {
    layer: 'entity',
    ops: [
      'is',
      'in',
    ],
  },
  claim: {
    layer: 'entity',
    ops: [
      'is',
      'in',
    ],
  },
  domain: {
    layer: 'entity',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
    ],
  },
  model: {
    layer: 'prompt',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
    ],
  },
  page: {
    layer: 'entity',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
    ],
  },
  persona: {
    layer: 'prompt',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
      'exists',
    ],
  },
  prompt: {
    layer: 'prompt',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
    ],
  },
  region: {
    layer: 'prompt',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
    ],
  },
  tag: {
    layer: 'prompt',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
      'exists',
    ],
  },
  theme: {
    layer: 'entity',
    ops: [
      'is',
      'in',
    ],
  },
  topic: {
    layer: 'prompt',
    ops: [
      'is',
      'not_is',
      'in',
      'not_in',
      'contains',
      'not_contains',
      'matches',
      'contains_case_insensitive',
      'not_contains_case_insensitive',
    ],
  },
} as const;
